version: '3'

services:
  portainer:
    image: cr.portainer.io/portainer/portainer-ce:2.11.0
    container_name: portainer
    restart: always
#    ports:
#      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
#      - /etc/letsencrypt/:/etc/letsencrypt/
#    command:
#      - --ssl
#      - --sslcert
#      - /etc/letsencrypt/live/bookingsimple.de/fullchain.pem
#      - --sslkey
#      - /etc/letsencrypt/live/bookingsimple.de/privkey.pem
#    environment:
#      - disable-tls
    ### ToDo: Change to your public DNS name
#      - VIRTUAL_HOST=bookingsimple.de
    restart: always
    networks:
      proxy_default:
        ipv4_address: 172.20.0.10


networks:
  proxy_default:
    external: true
volumes:
  portainer_data:
